// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/collection/collection.proto

package collection

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Collection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionID  int32                  `protobuf:"varint,1,opt,name=CollectionID,proto3" json:"CollectionID,omitempty"`
	AccountType   string                 `protobuf:"bytes,2,opt,name=AccountType,proto3" json:"AccountType,omitempty"`
	AccountNumber string                 `protobuf:"bytes,3,opt,name=AccountNumber,proto3" json:"AccountNumber,omitempty"`
	Sender        string                 `protobuf:"bytes,4,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=Date,proto3" json:"Date,omitempty"`
	Amount        int32                  `protobuf:"varint,6,opt,name=Amount,proto3" json:"Amount,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,8,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,10,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	DeletedBy     string                 `protobuf:"bytes,12,opt,name=DeletedBy,proto3" json:"DeletedBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_proto_collection_collection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_collection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_proto_collection_collection_proto_rawDescGZIP(), []int{0}
}

func (x *Collection) GetCollectionID() int32 {
	if x != nil {
		return x.CollectionID
	}
	return 0
}

func (x *Collection) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *Collection) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *Collection) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Collection) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Collection) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Collection) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Collection) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Collection) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Collection) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Collection) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Collection) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=SortBy,proto3" json:"SortBy,omitempty"`
	Order         string                 `protobuf:"bytes,4,opt,name=Order,proto3" json:"Order,omitempty"`
	SearchTerm    string                 `protobuf:"bytes,5,opt,name=SearchTerm,proto3" json:"SearchTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_proto_collection_collection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_collection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_collection_collection_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Filter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Filter) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *Filter) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Filter) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,2,opt,name=TotalAmount,proto3" json:"TotalAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_proto_collection_collection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_collection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_proto_collection_collection_proto_rawDescGZIP(), []int{2}
}

func (x *Stats) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Stats) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type CreateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coll          *Collection            `protobuf:"bytes,1,opt,name=coll,proto3" json:"coll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_proto_collection_collection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_collection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_collection_collection_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCollectionRequest) GetColl() *Collection {
	if x != nil {
		return x.Coll
	}
	return nil
}

type CreateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionID  string                 `protobuf:"bytes,1,opt,name=CollectionID,proto3" json:"CollectionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResponse) Reset() {
	*x = CreateCollectionResponse{}
	mi := &file_proto_collection_collection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResponse) ProtoMessage() {}

func (x *CreateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_collection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_collection_collection_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCollectionResponse) GetCollectionID() string {
	if x != nil {
		return x.CollectionID
	}
	return ""
}

type GetCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coll          *Collection            `protobuf:"bytes,1,opt,name=coll,proto3" json:"coll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionRequest) Reset() {
	*x = GetCollectionRequest{}
	mi := &file_proto_collection_collection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionRequest) ProtoMessage() {}

func (x *GetCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_collection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_collection_collection_proto_rawDescGZIP(), []int{5}
}

func (x *GetCollectionRequest) GetColl() *Collection {
	if x != nil {
		return x.Coll
	}
	return nil
}

type GetCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coll          *Collection            `protobuf:"bytes,1,opt,name=coll,proto3" json:"coll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionResponse) Reset() {
	*x = GetCollectionResponse{}
	mi := &file_proto_collection_collection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionResponse) ProtoMessage() {}

func (x *GetCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_collection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionResponse.ProtoReflect.Descriptor instead.
func (*GetCollectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_collection_collection_proto_rawDescGZIP(), []int{6}
}

func (x *GetCollectionResponse) GetColl() *Collection {
	if x != nil {
		return x.Coll
	}
	return nil
}

type UpdateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coll          *Collection            `protobuf:"bytes,1,opt,name=coll,proto3" json:"coll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollectionRequest) Reset() {
	*x = UpdateCollectionRequest{}
	mi := &file_proto_collection_collection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectionRequest) ProtoMessage() {}

func (x *UpdateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_collection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectionRequest.ProtoReflect.Descriptor instead.
func (*UpdateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_collection_collection_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCollectionRequest) GetColl() *Collection {
	if x != nil {
		return x.Coll
	}
	return nil
}

type UpdateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coll          *Collection            `protobuf:"bytes,1,opt,name=coll,proto3" json:"coll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollectionResponse) Reset() {
	*x = UpdateCollectionResponse{}
	mi := &file_proto_collection_collection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectionResponse) ProtoMessage() {}

func (x *UpdateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_collection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectionResponse.ProtoReflect.Descriptor instead.
func (*UpdateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_collection_collection_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCollectionResponse) GetColl() *Collection {
	if x != nil {
		return x.Coll
	}
	return nil
}

type DeleteCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coll          *Collection            `protobuf:"bytes,1,opt,name=coll,proto3" json:"coll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionRequest) Reset() {
	*x = DeleteCollectionRequest{}
	mi := &file_proto_collection_collection_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionRequest) ProtoMessage() {}

func (x *DeleteCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_collection_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCollectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_collection_collection_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCollectionRequest) GetColl() *Collection {
	if x != nil {
		return x.Coll
	}
	return nil
}

type DeleteCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionResponse) Reset() {
	*x = DeleteCollectionResponse{}
	mi := &file_proto_collection_collection_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionResponse) ProtoMessage() {}

func (x *DeleteCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_collection_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionResponse.ProtoReflect.Descriptor instead.
func (*DeleteCollectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_collection_collection_proto_rawDescGZIP(), []int{10}
}

type ListCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionRequest) Reset() {
	*x = ListCollectionRequest{}
	mi := &file_proto_collection_collection_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionRequest) ProtoMessage() {}

func (x *ListCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_collection_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_collection_collection_proto_rawDescGZIP(), []int{11}
}

func (x *ListCollectionRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coll          []*Collection          `protobuf:"bytes,1,rep,name=coll,proto3" json:"coll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionResponse) Reset() {
	*x = ListCollectionResponse{}
	mi := &file_proto_collection_collection_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionResponse) ProtoMessage() {}

func (x *ListCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_collection_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_collection_collection_proto_rawDescGZIP(), []int{12}
}

func (x *ListCollectionResponse) GetColl() []*Collection {
	if x != nil {
		return x.Coll
	}
	return nil
}

type CollectionStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionStatsRequest) Reset() {
	*x = CollectionStatsRequest{}
	mi := &file_proto_collection_collection_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionStatsRequest) ProtoMessage() {}

func (x *CollectionStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_collection_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionStatsRequest.ProtoReflect.Descriptor instead.
func (*CollectionStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_collection_collection_proto_rawDescGZIP(), []int{13}
}

func (x *CollectionStatsRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type CollectionStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *Stats                 `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionStatsResponse) Reset() {
	*x = CollectionStatsResponse{}
	mi := &file_proto_collection_collection_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionStatsResponse) ProtoMessage() {}

func (x *CollectionStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_collection_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionStatsResponse.ProtoReflect.Descriptor instead.
func (*CollectionStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_collection_collection_proto_rawDescGZIP(), []int{14}
}

func (x *CollectionStatsResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_proto_collection_collection_proto protoreflect.FileDescriptor

const file_proto_collection_collection_proto_rawDesc = "" +
	"\n" +
	"!proto/collection/collection.proto\x12\n" +
	"collection\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe0\x03\n" +
	"\n" +
	"Collection\x12\"\n" +
	"\fCollectionID\x18\x01 \x01(\x05R\fCollectionID\x12 \n" +
	"\vAccountType\x18\x02 \x01(\tR\vAccountType\x12$\n" +
	"\rAccountNumber\x18\x03 \x01(\tR\rAccountNumber\x12\x16\n" +
	"\x06Sender\x18\x04 \x01(\tR\x06Sender\x12.\n" +
	"\x04Date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04Date\x12\x16\n" +
	"\x06Amount\x18\x06 \x01(\x05R\x06Amount\x128\n" +
	"\tCreatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x12\x1c\n" +
	"\tCreatedBy\x18\b \x01(\tR\tCreatedBy\x128\n" +
	"\tUpdatedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x1c\n" +
	"\tUpdatedBy\x18\n" +
	" \x01(\tR\tUpdatedBy\x128\n" +
	"\tDeletedAt\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAt\x12\x1c\n" +
	"\tDeletedBy\x18\f \x01(\tR\tDeletedBy\"\x84\x01\n" +
	"\x06Filter\x12\x16\n" +
	"\x06Offset\x18\x01 \x01(\x05R\x06Offset\x12\x14\n" +
	"\x05Limit\x18\x02 \x01(\x05R\x05Limit\x12\x16\n" +
	"\x06SortBy\x18\x03 \x01(\tR\x06SortBy\x12\x14\n" +
	"\x05Order\x18\x04 \x01(\tR\x05Order\x12\x1e\n" +
	"\n" +
	"SearchTerm\x18\x05 \x01(\tR\n" +
	"SearchTerm\"?\n" +
	"\x05Stats\x12\x14\n" +
	"\x05Count\x18\x01 \x01(\x05R\x05Count\x12 \n" +
	"\vTotalAmount\x18\x02 \x01(\x05R\vTotalAmount\"E\n" +
	"\x17CreateCollectionRequest\x12*\n" +
	"\x04coll\x18\x01 \x01(\v2\x16.collection.CollectionR\x04coll\">\n" +
	"\x18CreateCollectionResponse\x12\"\n" +
	"\fCollectionID\x18\x01 \x01(\tR\fCollectionID\"B\n" +
	"\x14GetCollectionRequest\x12*\n" +
	"\x04coll\x18\x01 \x01(\v2\x16.collection.CollectionR\x04coll\"C\n" +
	"\x15GetCollectionResponse\x12*\n" +
	"\x04coll\x18\x01 \x01(\v2\x16.collection.CollectionR\x04coll\"E\n" +
	"\x17UpdateCollectionRequest\x12*\n" +
	"\x04coll\x18\x01 \x01(\v2\x16.collection.CollectionR\x04coll\"F\n" +
	"\x18UpdateCollectionResponse\x12*\n" +
	"\x04coll\x18\x01 \x01(\v2\x16.collection.CollectionR\x04coll\"E\n" +
	"\x17DeleteCollectionRequest\x12*\n" +
	"\x04coll\x18\x01 \x01(\v2\x16.collection.CollectionR\x04coll\"\x1a\n" +
	"\x18DeleteCollectionResponse\"C\n" +
	"\x15ListCollectionRequest\x12*\n" +
	"\x06filter\x18\x01 \x01(\v2\x12.collection.FilterR\x06filter\"D\n" +
	"\x16ListCollectionResponse\x12*\n" +
	"\x04coll\x18\x01 \x03(\v2\x16.collection.CollectionR\x04coll\"D\n" +
	"\x16CollectionStatsRequest\x12*\n" +
	"\x06filter\x18\x01 \x01(\v2\x12.collection.FilterR\x06filter\"B\n" +
	"\x17CollectionStatsResponse\x12'\n" +
	"\x05stats\x18\x01 \x01(\v2\x11.collection.StatsR\x05stats2\xc7\x04\n" +
	"\x11CollectionService\x12_\n" +
	"\x10CreateCollection\x12#.collection.CreateCollectionRequest\x1a$.collection.CreateCollectionResponse\"\x00\x12V\n" +
	"\rGetCollection\x12 .collection.GetCollectionRequest\x1a!.collection.GetCollectionResponse\"\x00\x12_\n" +
	"\x10UpdateCollection\x12#.collection.UpdateCollectionRequest\x1a$.collection.UpdateCollectionResponse\"\x00\x12_\n" +
	"\x10DeleteCollection\x12#.collection.DeleteCollectionRequest\x1a$.collection.DeleteCollectionResponse\"\x00\x12Y\n" +
	"\x0eListCollection\x12!.collection.ListCollectionRequest\x1a\".collection.ListCollectionResponse\"\x00\x12\\\n" +
	"\x0fCollectionStats\x12\".collection.CollectionStatsRequest\x1a#.collection.CollectionStatsResponse\"\x00B\x14Z\x12./proto/collectionb\x06proto3"

var (
	file_proto_collection_collection_proto_rawDescOnce sync.Once
	file_proto_collection_collection_proto_rawDescData []byte
)

func file_proto_collection_collection_proto_rawDescGZIP() []byte {
	file_proto_collection_collection_proto_rawDescOnce.Do(func() {
		file_proto_collection_collection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_collection_collection_proto_rawDesc), len(file_proto_collection_collection_proto_rawDesc)))
	})
	return file_proto_collection_collection_proto_rawDescData
}

var file_proto_collection_collection_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_collection_collection_proto_goTypes = []any{
	(*Collection)(nil),               // 0: collection.Collection
	(*Filter)(nil),                   // 1: collection.Filter
	(*Stats)(nil),                    // 2: collection.Stats
	(*CreateCollectionRequest)(nil),  // 3: collection.CreateCollectionRequest
	(*CreateCollectionResponse)(nil), // 4: collection.CreateCollectionResponse
	(*GetCollectionRequest)(nil),     // 5: collection.GetCollectionRequest
	(*GetCollectionResponse)(nil),    // 6: collection.GetCollectionResponse
	(*UpdateCollectionRequest)(nil),  // 7: collection.UpdateCollectionRequest
	(*UpdateCollectionResponse)(nil), // 8: collection.UpdateCollectionResponse
	(*DeleteCollectionRequest)(nil),  // 9: collection.DeleteCollectionRequest
	(*DeleteCollectionResponse)(nil), // 10: collection.DeleteCollectionResponse
	(*ListCollectionRequest)(nil),    // 11: collection.ListCollectionRequest
	(*ListCollectionResponse)(nil),   // 12: collection.ListCollectionResponse
	(*CollectionStatsRequest)(nil),   // 13: collection.CollectionStatsRequest
	(*CollectionStatsResponse)(nil),  // 14: collection.CollectionStatsResponse
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
}
var file_proto_collection_collection_proto_depIdxs = []int32{
	15, // 0: collection.Collection.Date:type_name -> google.protobuf.Timestamp
	15, // 1: collection.Collection.CreatedAt:type_name -> google.protobuf.Timestamp
	15, // 2: collection.Collection.UpdatedAt:type_name -> google.protobuf.Timestamp
	15, // 3: collection.Collection.DeletedAt:type_name -> google.protobuf.Timestamp
	0,  // 4: collection.CreateCollectionRequest.coll:type_name -> collection.Collection
	0,  // 5: collection.GetCollectionRequest.coll:type_name -> collection.Collection
	0,  // 6: collection.GetCollectionResponse.coll:type_name -> collection.Collection
	0,  // 7: collection.UpdateCollectionRequest.coll:type_name -> collection.Collection
	0,  // 8: collection.UpdateCollectionResponse.coll:type_name -> collection.Collection
	0,  // 9: collection.DeleteCollectionRequest.coll:type_name -> collection.Collection
	1,  // 10: collection.ListCollectionRequest.filter:type_name -> collection.Filter
	0,  // 11: collection.ListCollectionResponse.coll:type_name -> collection.Collection
	1,  // 12: collection.CollectionStatsRequest.filter:type_name -> collection.Filter
	2,  // 13: collection.CollectionStatsResponse.stats:type_name -> collection.Stats
	3,  // 14: collection.CollectionService.CreateCollection:input_type -> collection.CreateCollectionRequest
	5,  // 15: collection.CollectionService.GetCollection:input_type -> collection.GetCollectionRequest
	7,  // 16: collection.CollectionService.UpdateCollection:input_type -> collection.UpdateCollectionRequest
	9,  // 17: collection.CollectionService.DeleteCollection:input_type -> collection.DeleteCollectionRequest
	11, // 18: collection.CollectionService.ListCollection:input_type -> collection.ListCollectionRequest
	13, // 19: collection.CollectionService.CollectionStats:input_type -> collection.CollectionStatsRequest
	4,  // 20: collection.CollectionService.CreateCollection:output_type -> collection.CreateCollectionResponse
	6,  // 21: collection.CollectionService.GetCollection:output_type -> collection.GetCollectionResponse
	8,  // 22: collection.CollectionService.UpdateCollection:output_type -> collection.UpdateCollectionResponse
	10, // 23: collection.CollectionService.DeleteCollection:output_type -> collection.DeleteCollectionResponse
	12, // 24: collection.CollectionService.ListCollection:output_type -> collection.ListCollectionResponse
	14, // 25: collection.CollectionService.CollectionStats:output_type -> collection.CollectionStatsResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_collection_collection_proto_init() }
func file_proto_collection_collection_proto_init() {
	if File_proto_collection_collection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_collection_collection_proto_rawDesc), len(file_proto_collection_collection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_collection_collection_proto_goTypes,
		DependencyIndexes: file_proto_collection_collection_proto_depIdxs,
		MessageInfos:      file_proto_collection_collection_proto_msgTypes,
	}.Build()
	File_proto_collection_collection_proto = out.File
	file_proto_collection_collection_proto_goTypes = nil
	file_proto_collection_collection_proto_depIdxs = nil
}
