// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/dailyReport/dailyReport.proto

package dailyReport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DailyReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportID      int32                  `protobuf:"varint,1,opt,name=ReportID,proto3" json:"ReportID,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=Date,proto3" json:"Date,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=Currency,proto3" json:"Currency,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,6,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,8,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	DeletedBy     string                 `protobuf:"bytes,10,opt,name=DeletedBy,proto3" json:"DeletedBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyReport) Reset() {
	*x = DailyReport{}
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyReport) ProtoMessage() {}

func (x *DailyReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyReport.ProtoReflect.Descriptor instead.
func (*DailyReport) Descriptor() ([]byte, []int) {
	return file_proto_dailyReport_dailyReport_proto_rawDescGZIP(), []int{0}
}

func (x *DailyReport) GetReportID() int32 {
	if x != nil {
		return x.ReportID
	}
	return 0
}

func (x *DailyReport) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyReport) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DailyReport) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DailyReport) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DailyReport) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *DailyReport) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DailyReport) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *DailyReport) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *DailyReport) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=SortBy,proto3" json:"SortBy,omitempty"`
	Order         string                 `protobuf:"bytes,4,opt,name=Order,proto3" json:"Order,omitempty"`
	SearchTerm    string                 `protobuf:"bytes,5,opt,name=SearchTerm,proto3" json:"SearchTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_dailyReport_dailyReport_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Filter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Filter) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *Filter) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Filter) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,2,opt,name=TotalAmount,proto3" json:"TotalAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_proto_dailyReport_dailyReport_proto_rawDescGZIP(), []int{2}
}

func (x *Stats) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Stats) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type CreateDailyReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dre           *DailyReport           `protobuf:"bytes,1,opt,name=Dre,proto3" json:"Dre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDailyReportRequest) Reset() {
	*x = CreateDailyReportRequest{}
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDailyReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDailyReportRequest) ProtoMessage() {}

func (x *CreateDailyReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDailyReportRequest.ProtoReflect.Descriptor instead.
func (*CreateDailyReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_dailyReport_dailyReport_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDailyReportRequest) GetDre() *DailyReport {
	if x != nil {
		return x.Dre
	}
	return nil
}

type CreateDailyReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportID      int32                  `protobuf:"varint,1,opt,name=ReportID,proto3" json:"ReportID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDailyReportResponse) Reset() {
	*x = CreateDailyReportResponse{}
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDailyReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDailyReportResponse) ProtoMessage() {}

func (x *CreateDailyReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDailyReportResponse.ProtoReflect.Descriptor instead.
func (*CreateDailyReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_dailyReport_dailyReport_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDailyReportResponse) GetReportID() int32 {
	if x != nil {
		return x.ReportID
	}
	return 0
}

type GetDailyReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dre           *DailyReport           `protobuf:"bytes,1,opt,name=Dre,proto3" json:"Dre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyReportRequest) Reset() {
	*x = GetDailyReportRequest{}
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyReportRequest) ProtoMessage() {}

func (x *GetDailyReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyReportRequest.ProtoReflect.Descriptor instead.
func (*GetDailyReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_dailyReport_dailyReport_proto_rawDescGZIP(), []int{5}
}

func (x *GetDailyReportRequest) GetDre() *DailyReport {
	if x != nil {
		return x.Dre
	}
	return nil
}

type GetDailyReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dre           *DailyReport           `protobuf:"bytes,1,opt,name=Dre,proto3" json:"Dre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyReportResponse) Reset() {
	*x = GetDailyReportResponse{}
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyReportResponse) ProtoMessage() {}

func (x *GetDailyReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyReportResponse.ProtoReflect.Descriptor instead.
func (*GetDailyReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_dailyReport_dailyReport_proto_rawDescGZIP(), []int{6}
}

func (x *GetDailyReportResponse) GetDre() *DailyReport {
	if x != nil {
		return x.Dre
	}
	return nil
}

type UpdateDailyReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dre           *DailyReport           `protobuf:"bytes,1,opt,name=Dre,proto3" json:"Dre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDailyReportRequest) Reset() {
	*x = UpdateDailyReportRequest{}
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDailyReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDailyReportRequest) ProtoMessage() {}

func (x *UpdateDailyReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDailyReportRequest.ProtoReflect.Descriptor instead.
func (*UpdateDailyReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_dailyReport_dailyReport_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDailyReportRequest) GetDre() *DailyReport {
	if x != nil {
		return x.Dre
	}
	return nil
}

type UpdateDailyReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dre           *DailyReport           `protobuf:"bytes,1,opt,name=Dre,proto3" json:"Dre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDailyReportResponse) Reset() {
	*x = UpdateDailyReportResponse{}
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDailyReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDailyReportResponse) ProtoMessage() {}

func (x *UpdateDailyReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDailyReportResponse.ProtoReflect.Descriptor instead.
func (*UpdateDailyReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_dailyReport_dailyReport_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDailyReportResponse) GetDre() *DailyReport {
	if x != nil {
		return x.Dre
	}
	return nil
}

type DeleteDailyReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dre           *DailyReport           `protobuf:"bytes,1,opt,name=Dre,proto3" json:"Dre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDailyReportRequest) Reset() {
	*x = DeleteDailyReportRequest{}
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDailyReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDailyReportRequest) ProtoMessage() {}

func (x *DeleteDailyReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDailyReportRequest.ProtoReflect.Descriptor instead.
func (*DeleteDailyReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_dailyReport_dailyReport_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDailyReportRequest) GetDre() *DailyReport {
	if x != nil {
		return x.Dre
	}
	return nil
}

type DeleteDailyReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDailyReportResponse) Reset() {
	*x = DeleteDailyReportResponse{}
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDailyReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDailyReportResponse) ProtoMessage() {}

func (x *DeleteDailyReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDailyReportResponse.ProtoReflect.Descriptor instead.
func (*DeleteDailyReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_dailyReport_dailyReport_proto_rawDescGZIP(), []int{10}
}

type ListDailyReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDailyReportRequest) Reset() {
	*x = ListDailyReportRequest{}
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDailyReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDailyReportRequest) ProtoMessage() {}

func (x *ListDailyReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDailyReportRequest.ProtoReflect.Descriptor instead.
func (*ListDailyReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_dailyReport_dailyReport_proto_rawDescGZIP(), []int{11}
}

func (x *ListDailyReportRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListDailyReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dre           []*DailyReport         `protobuf:"bytes,1,rep,name=Dre,proto3" json:"Dre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDailyReportResponse) Reset() {
	*x = ListDailyReportResponse{}
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDailyReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDailyReportResponse) ProtoMessage() {}

func (x *ListDailyReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDailyReportResponse.ProtoReflect.Descriptor instead.
func (*ListDailyReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_dailyReport_dailyReport_proto_rawDescGZIP(), []int{12}
}

func (x *ListDailyReportResponse) GetDre() []*DailyReport {
	if x != nil {
		return x.Dre
	}
	return nil
}

type DailyReportStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyReportStatsRequest) Reset() {
	*x = DailyReportStatsRequest{}
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyReportStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyReportStatsRequest) ProtoMessage() {}

func (x *DailyReportStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyReportStatsRequest.ProtoReflect.Descriptor instead.
func (*DailyReportStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_dailyReport_dailyReport_proto_rawDescGZIP(), []int{13}
}

func (x *DailyReportStatsRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type DailyReportStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *Stats                 `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyReportStatsResponse) Reset() {
	*x = DailyReportStatsResponse{}
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyReportStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyReportStatsResponse) ProtoMessage() {}

func (x *DailyReportStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dailyReport_dailyReport_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyReportStatsResponse.ProtoReflect.Descriptor instead.
func (*DailyReportStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_dailyReport_dailyReport_proto_rawDescGZIP(), []int{14}
}

func (x *DailyReportStatsResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_proto_dailyReport_dailyReport_proto protoreflect.FileDescriptor

const file_proto_dailyReport_dailyReport_proto_rawDesc = "" +
	"\n" +
	"#proto/dailyReport/dailyReport.proto\x12\vdailyreport\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x02\n" +
	"\vDailyReport\x12\x1a\n" +
	"\bReportID\x18\x01 \x01(\x05R\bReportID\x12\x12\n" +
	"\x04Date\x18\x02 \x01(\tR\x04Date\x12\x16\n" +
	"\x06Amount\x18\x03 \x01(\x05R\x06Amount\x12\x1a\n" +
	"\bCurrency\x18\x04 \x01(\tR\bCurrency\x128\n" +
	"\tCreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x12\x1c\n" +
	"\tCreatedBy\x18\x06 \x01(\tR\tCreatedBy\x128\n" +
	"\tUpdatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x1c\n" +
	"\tUpdatedBy\x18\b \x01(\tR\tUpdatedBy\x128\n" +
	"\tDeletedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAt\x12\x1c\n" +
	"\tDeletedBy\x18\n" +
	" \x01(\tR\tDeletedBy\"\x84\x01\n" +
	"\x06Filter\x12\x16\n" +
	"\x06Offset\x18\x01 \x01(\x05R\x06Offset\x12\x14\n" +
	"\x05Limit\x18\x02 \x01(\x05R\x05Limit\x12\x16\n" +
	"\x06SortBy\x18\x03 \x01(\tR\x06SortBy\x12\x14\n" +
	"\x05Order\x18\x04 \x01(\tR\x05Order\x12\x1e\n" +
	"\n" +
	"SearchTerm\x18\x05 \x01(\tR\n" +
	"SearchTerm\"?\n" +
	"\x05Stats\x12\x14\n" +
	"\x05Count\x18\x01 \x01(\x05R\x05Count\x12 \n" +
	"\vTotalAmount\x18\x02 \x01(\x05R\vTotalAmount\"F\n" +
	"\x18CreateDailyReportRequest\x12*\n" +
	"\x03Dre\x18\x01 \x01(\v2\x18.dailyreport.DailyReportR\x03Dre\"7\n" +
	"\x19CreateDailyReportResponse\x12\x1a\n" +
	"\bReportID\x18\x01 \x01(\x05R\bReportID\"C\n" +
	"\x15GetDailyReportRequest\x12*\n" +
	"\x03Dre\x18\x01 \x01(\v2\x18.dailyreport.DailyReportR\x03Dre\"D\n" +
	"\x16GetDailyReportResponse\x12*\n" +
	"\x03Dre\x18\x01 \x01(\v2\x18.dailyreport.DailyReportR\x03Dre\"F\n" +
	"\x18UpdateDailyReportRequest\x12*\n" +
	"\x03Dre\x18\x01 \x01(\v2\x18.dailyreport.DailyReportR\x03Dre\"G\n" +
	"\x19UpdateDailyReportResponse\x12*\n" +
	"\x03Dre\x18\x01 \x01(\v2\x18.dailyreport.DailyReportR\x03Dre\"F\n" +
	"\x18DeleteDailyReportRequest\x12*\n" +
	"\x03Dre\x18\x01 \x01(\v2\x18.dailyreport.DailyReportR\x03Dre\"\x1b\n" +
	"\x19DeleteDailyReportResponse\"E\n" +
	"\x16ListDailyReportRequest\x12+\n" +
	"\x06filter\x18\x01 \x01(\v2\x13.dailyreport.FilterR\x06filter\"E\n" +
	"\x17ListDailyReportResponse\x12*\n" +
	"\x03Dre\x18\x01 \x03(\v2\x18.dailyreport.DailyReportR\x03Dre\"F\n" +
	"\x17DailyReportStatsRequest\x12+\n" +
	"\x06filter\x18\x01 \x01(\v2\x13.dailyreport.FilterR\x06filter\"D\n" +
	"\x18DailyReportStatsResponse\x12(\n" +
	"\x05stats\x18\x01 \x01(\v2\x12.dailyreport.StatsR\x05stats2\xe6\x04\n" +
	"\x12DailyReportService\x12d\n" +
	"\x11CreateDailyReport\x12%.dailyreport.CreateDailyReportRequest\x1a&.dailyreport.CreateDailyReportResponse\"\x00\x12[\n" +
	"\x0eGetDailyReport\x12\".dailyreport.GetDailyReportRequest\x1a#.dailyreport.GetDailyReportResponse\"\x00\x12d\n" +
	"\x11UpdateDailyReport\x12%.dailyreport.UpdateDailyReportRequest\x1a&.dailyreport.UpdateDailyReportResponse\"\x00\x12d\n" +
	"\x11DeleteDailyReport\x12%.dailyreport.DeleteDailyReportRequest\x1a&.dailyreport.DeleteDailyReportResponse\"\x00\x12^\n" +
	"\x0fListDailyReport\x12#.dailyreport.ListDailyReportRequest\x1a$.dailyreport.ListDailyReportResponse\"\x00\x12a\n" +
	"\x10DailyReportStats\x12$.dailyreport.DailyReportStatsRequest\x1a%.dailyreport.DailyReportStatsResponse\"\x00B\x15Z\x13./proto/dailyReportb\x06proto3"

var (
	file_proto_dailyReport_dailyReport_proto_rawDescOnce sync.Once
	file_proto_dailyReport_dailyReport_proto_rawDescData []byte
)

func file_proto_dailyReport_dailyReport_proto_rawDescGZIP() []byte {
	file_proto_dailyReport_dailyReport_proto_rawDescOnce.Do(func() {
		file_proto_dailyReport_dailyReport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dailyReport_dailyReport_proto_rawDesc), len(file_proto_dailyReport_dailyReport_proto_rawDesc)))
	})
	return file_proto_dailyReport_dailyReport_proto_rawDescData
}

var file_proto_dailyReport_dailyReport_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_dailyReport_dailyReport_proto_goTypes = []any{
	(*DailyReport)(nil),               // 0: dailyreport.DailyReport
	(*Filter)(nil),                    // 1: dailyreport.Filter
	(*Stats)(nil),                     // 2: dailyreport.Stats
	(*CreateDailyReportRequest)(nil),  // 3: dailyreport.CreateDailyReportRequest
	(*CreateDailyReportResponse)(nil), // 4: dailyreport.CreateDailyReportResponse
	(*GetDailyReportRequest)(nil),     // 5: dailyreport.GetDailyReportRequest
	(*GetDailyReportResponse)(nil),    // 6: dailyreport.GetDailyReportResponse
	(*UpdateDailyReportRequest)(nil),  // 7: dailyreport.UpdateDailyReportRequest
	(*UpdateDailyReportResponse)(nil), // 8: dailyreport.UpdateDailyReportResponse
	(*DeleteDailyReportRequest)(nil),  // 9: dailyreport.DeleteDailyReportRequest
	(*DeleteDailyReportResponse)(nil), // 10: dailyreport.DeleteDailyReportResponse
	(*ListDailyReportRequest)(nil),    // 11: dailyreport.ListDailyReportRequest
	(*ListDailyReportResponse)(nil),   // 12: dailyreport.ListDailyReportResponse
	(*DailyReportStatsRequest)(nil),   // 13: dailyreport.DailyReportStatsRequest
	(*DailyReportStatsResponse)(nil),  // 14: dailyreport.DailyReportStatsResponse
	(*timestamppb.Timestamp)(nil),     // 15: google.protobuf.Timestamp
}
var file_proto_dailyReport_dailyReport_proto_depIdxs = []int32{
	15, // 0: dailyreport.DailyReport.CreatedAt:type_name -> google.protobuf.Timestamp
	15, // 1: dailyreport.DailyReport.UpdatedAt:type_name -> google.protobuf.Timestamp
	15, // 2: dailyreport.DailyReport.DeletedAt:type_name -> google.protobuf.Timestamp
	0,  // 3: dailyreport.CreateDailyReportRequest.Dre:type_name -> dailyreport.DailyReport
	0,  // 4: dailyreport.GetDailyReportRequest.Dre:type_name -> dailyreport.DailyReport
	0,  // 5: dailyreport.GetDailyReportResponse.Dre:type_name -> dailyreport.DailyReport
	0,  // 6: dailyreport.UpdateDailyReportRequest.Dre:type_name -> dailyreport.DailyReport
	0,  // 7: dailyreport.UpdateDailyReportResponse.Dre:type_name -> dailyreport.DailyReport
	0,  // 8: dailyreport.DeleteDailyReportRequest.Dre:type_name -> dailyreport.DailyReport
	1,  // 9: dailyreport.ListDailyReportRequest.filter:type_name -> dailyreport.Filter
	0,  // 10: dailyreport.ListDailyReportResponse.Dre:type_name -> dailyreport.DailyReport
	1,  // 11: dailyreport.DailyReportStatsRequest.filter:type_name -> dailyreport.Filter
	2,  // 12: dailyreport.DailyReportStatsResponse.stats:type_name -> dailyreport.Stats
	3,  // 13: dailyreport.DailyReportService.CreateDailyReport:input_type -> dailyreport.CreateDailyReportRequest
	5,  // 14: dailyreport.DailyReportService.GetDailyReport:input_type -> dailyreport.GetDailyReportRequest
	7,  // 15: dailyreport.DailyReportService.UpdateDailyReport:input_type -> dailyreport.UpdateDailyReportRequest
	9,  // 16: dailyreport.DailyReportService.DeleteDailyReport:input_type -> dailyreport.DeleteDailyReportRequest
	11, // 17: dailyreport.DailyReportService.ListDailyReport:input_type -> dailyreport.ListDailyReportRequest
	13, // 18: dailyreport.DailyReportService.DailyReportStats:input_type -> dailyreport.DailyReportStatsRequest
	4,  // 19: dailyreport.DailyReportService.CreateDailyReport:output_type -> dailyreport.CreateDailyReportResponse
	6,  // 20: dailyreport.DailyReportService.GetDailyReport:output_type -> dailyreport.GetDailyReportResponse
	8,  // 21: dailyreport.DailyReportService.UpdateDailyReport:output_type -> dailyreport.UpdateDailyReportResponse
	10, // 22: dailyreport.DailyReportService.DeleteDailyReport:output_type -> dailyreport.DeleteDailyReportResponse
	12, // 23: dailyreport.DailyReportService.ListDailyReport:output_type -> dailyreport.ListDailyReportResponse
	14, // 24: dailyreport.DailyReportService.DailyReportStats:output_type -> dailyreport.DailyReportStatsResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_dailyReport_dailyReport_proto_init() }
func file_proto_dailyReport_dailyReport_proto_init() {
	if File_proto_dailyReport_dailyReport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dailyReport_dailyReport_proto_rawDesc), len(file_proto_dailyReport_dailyReport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dailyReport_dailyReport_proto_goTypes,
		DependencyIndexes: file_proto_dailyReport_dailyReport_proto_depIdxs,
		MessageInfos:      file_proto_dailyReport_dailyReport_proto_msgTypes,
	}.Build()
	File_proto_dailyReport_dailyReport_proto = out.File
	file_proto_dailyReport_dailyReport_proto_goTypes = nil
	file_proto_dailyReport_dailyReport_proto_depIdxs = nil
}
